/*
* Generated file
*
* Generated from: yang module name: state-machine yang module local name: machine
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jan 22 22:56:52 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.state_machine;
public interface MachineModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getUpgrade();

    public void setUpgrade(javax.management.ObjectName upgrade);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getIsolation();

    public void setIsolation(javax.management.ObjectName isolation);

    public javax.management.ObjectName getBroker();

    public void setBroker(javax.management.ObjectName broker);

}
