/*
* Generated file
*
* Generated from: yang module name: state-machine yang module local name: machine
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jan 22 22:46:32 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.state_machine;
public class MachineModuleFactory extends org.opendaylight.controller.config.yang.config.state_machine.AbstractMachineModuleFactory {

}
